app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*Route::bind('siswa',function ($siswa)
{
return App\Siswa::find($siswa);
});
Route::resource('siswa','SiswaController');*/


Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::get('artikel', 'ArtikelController@index');

Route::get('artikel/add', 'ArtikelController@create');

Route::post('artikel/save', 'ArtikelController@store');

Route::post('artikel/update', 'ArtikelController@update');

Route::get('artikel/edit/{id}', 'ArtikelController@edit');

Route::post('komentar', 'ArtikelController@komentar');

Route::get('load_comments/{id}',function ($id)
{
	$data = App\Komentar::where('idposts',$id)->get();
	echo json_encode($data);
});

Route::get('/images/{filename}',
	function ($filename)
{
	$path = storage_path() . '/' .$filename;

	$file = File::get($path);
	$type = File::mimeType($path);

	$response = Response::make($file,200);
	$response->header("Content-Type", $type);

	return $response;
});

Route::get('/pdf/{slug}','WelcomeController@showpdf');

Route::get('/{slug}', 'ArtikelController@show');

Route::get('/mail/{slug}', function ($slug)
{
	$artikel = \App\Posts::where('slug',$slug)->first();

	Mail::send('artikel.pdf', ['data' => $artikel],
		function($message)
	{
		$message->to(Auth::user()->email, Auth::user()->name)
		->subject("Update Artikel");
	});

	return redirect(url());
});

Route::get('api/artikel/all',function()
{
	$data = \App\Posts::all();

	$arr = array();

	foreach ($data as $key) {
		$arr[] = array(
			'slug'=>$key['slug'],
			'isi'=>$key['isi'],
			'create_at'=>$key['created_at'],
			'author'=>\App\User::find($key['idpengguna'])['email'],
			'tag'=>$key['tag'],
			'sampul'=>url('images/'.$key['sampul']),
			'judul'=>$key['judul']
			);
	}


	echo json_encode($arr);

	// $data = array('artikel'=>
	// 			array('id'=>1,
	// 				'judul'=>'judul artikel',
	// 				'isi'=>'isi artikel',
	// 				'timestamps'=>'2015-01-01 01:01:01')
	// 			);

	// // echo "<pre>".print_r($data,1)."</pre>";
	// // echo $data->artikel->id;
	// // echo $data['artikel']['id'];

	// $json = json_encode($data);
	// echo $json;

	// // $obj = json_decode($json);

	// // echo "<pre>".print_r($obj,1)."</pre>";
	// // echo $obj['artikel']['id'];
});

Route::get('api/artikel/detail/{slug}',function($slug)
{
	$key = \App\Posts::where('slug',$slug)->first();

		$arr = array(
			'slug'=>$key['slug'],
			'isi'=>$key['isi'],
			'create_at'=>$key['created_at'],
			'author'=>\App\User::find($key['idpengguna'])['email'],
			'tag'=>$key['tag'],
			'sampul'=>url('images/'.$key['sampul']),
			'judul'=>$key['judul']
		);


	if(sizeof($key)==0){
		$data = array('status'=>"Error",
					'error_code'=>404,
					'name'=>'artikel_notfound',
					'msg'=>'Artikel Not Found');
		echo json_encode($data);
	}else{
	echo json_encode($arr);
	}
});

Route::get('api/artikel/{type}/{cari}',function($type,$cari)
{

	$type = array('idpengguna','judul','slug','tags');

	if(in_array($type, $avail)){

		$data = \App\Posts::where($type,$cari)->get();

		$arr = array();

		foreach ($data as $key) {
			$arr[] = array(
				'slug'=>$key['slug'],
				'isi'=>$key['isi'],
				'create_at'=>$key['created_at'],
				'author'=>\App\User::find($key['idpengguna'])['email'],
				'tag'=>$key['tag'],
				'sampul'=>url('images/'.$key['sampul']),
				'judul'=>$key['judul']
				);
		}

		
		if(sizeof($data)==0){
			$data = array('status'=>"Error",
						'error_code'=>404,
						'name'=>'artikel_notfound',
						'msg'=>'Artikel Not Found');
			echo json_encode($data);
		}else{
		echo json_encode($arr);
		}
	}else{
		if(sizeof($data)==0){
			$data = array('status'=>"Error",
						'error_code'=>304,
						'name'=>'type_notfound',
						'msg'=>'Type Not Found');
			echo json_encode($data);
		}
	}	
});

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

/*Route::get('checkpdf/{value?}', function($value='HELLO')
{
	$pdf = App::make('dompdf.wrapper');
	$pdf->loadHTML('<h1>'.$value.'</h1>');
	return $pdf->stream();
});*/

app/Siswa.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model {

	//

}

app/Http/Controllers/SiswaController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Siswa as Siswa;

use Illuminate\Http\Request;

class SiswaController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(Siswa $siswa)
	{
		$siswas = $siswa->get();
		return view('siswa.list',compact('siswas'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create(Siswa $siswa)
	{
		return view('siswa.add',compact('siswa'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $req, Siswa $siswa)
	{
		$siswas = new $siswa;
		$siswas->nama = $req->nama;
		$siswas->jenis_kelamin = $req->jenis_kelamin;
		$siswas->tanggal_lahir = date_format(date_create($req->tanggal_lahir),"Y-m-d");
		$siswas->save();
		return redirect('siswa');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show(Siswa $siswa)
	{
		return view('siswa.detail',compact('siswa'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit(Siswa $siswa)
	{
		return view('siswa.edit',compact('siswa'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(Request $req, Siswa $siswa)
	{
		$siswa->nama = $req->nama;
		$siswa->jenis_kelamin = $req->jenis_kelamin;
		$siswa->tanggal_lahir = date_format(date_create($req->tanggal_lahir),"Y-m-d");
		$siswa->save();
		return redirect('siswa');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy(Siswa $siswa)
	{
		$siswa->delete();
		return redirect('siswa');
	}

}

resources/views/siswa/add.blade.php
@extends('app')
@section('content')
<div class="container">
{!! link_to_route("siswa.index","Siswa") !!}
<hr>
{!! Form::model($siswa,['route'=>['siswa.store',$siswa->id],'method'=>'POST']) !!}
@include ('siswa.form')
{!! Form::close() !!}
</div>
@endsection

resources/views/siswa/detail.blade.php
@extends('app')
@section('content')
<div class="container">
{!! link_to_route("siswa.index","Siswa") !!}
<hr>
{{ $siswa->nama }}<br>
{{ $siswa->jenis_kelamin }}<br>
{{ $siswa->tanggal_lahir }}
<hr>
{!! link_to_route("siswa.edit","Edit",$siswa->id) !!}
{!! Form::open(['method'=>'DELETE','route'=>['siswa.destroy',$siswa->id]]) !!}
{!! Form::submit('Delete',['style'=>'background-color:
transparent;border:0px;padding:0px;color:
#337ab7;text-decoration: none;','onclick'=>'return confirm("Are
you sure?")']) !!}
{!! Form::close() !!}
</div>
@endsection

resources/views/siswa/edit.blade.php
@extends('app')
@section('content')
<div class="container">
{!! link_to_route("siswa.index","Siswa") !!}
<hr>
{!! Form::model($siswa,
['route'=>['siswa.update',$siswa->id],'method'=>'PATCH']) !!}
@include ('siswa.form')
{!! Form::close() !!}
</div>
@endsection

resources/views/siswa/form.blade.php
<div class="form-group">
{!! Form::label('nama') !!}
{!! Form::text('nama',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
{!! Form::label('jenis_kelamin') !!}
{!! Form::text('jenis_kelamin',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
{!! Form::label('tanggal_lahir') !!}
{!! Form::text('tanggal_lahir',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
{!! Form::submit('Send',null,['class'=>'form-control']) !!}
</div>

resources/views/siswa/list.blade.php
@extends('app')
@section('content')
<div class="container">
{!! link_to_route("siswa.index","Siswa") !!}
<hr>
{!! link_to_route("siswa.create","New") !!}
<ul>
@foreach ($siswas as $data)
<li>
{!! link_to_route("siswa.show",$data->nama,$data->id) !!}
</li>
@endforeach
</ul>
</div>
@endsection